version: '3.5'

networks:
  localdev:
    name: localdev
    
services:
  main-api:
    build: YAPI/
    restart: always
    ports:
      - "7000:80"
    depends_on:
      - db-server
      - redis
    networks:
      - localdev
        
  db-server:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_YAV_PASSWORD=9585200
      - MSSQL_TCP_PORT=1433
    ports:
      - "1400:1433"
    networks:
      - localdev
  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - localdev